//
//  SBProximityFilter.h
//  SmartBeacon-SDK
//
//  Created by Ludovic Riviere on 13/01/2014.
//  Copyright (c) 2014 IP Stand. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>


/**
 *  SBProximityFilter
 *
 *  Use this class for get smoothed proximity value.
 *
 */
@interface SBProximityFilter : NSObject


/**
 * Max values stored in cache for calculate average.
 */
@property (nonatomic) int historyMaxValues;     // default is 20


/**
 *  Get shared instance.
 */
+ (id)sharedInstance;


/**
 *  Add a new value of beacon ID.
 *
 *  @param proximityValue New proximity value to add.
 *  @param beaconId The Beacon ID generated by SBUtilily uniqueIDForBeacon:.
 */
- (void)addProximityValue:(CLProximity)proximityValue forBeaconId:(NSString *)beaconId;


/**
 *  Get the average of proximity given by beacon ID.
 *
 *  @param beaconId The Beacon ID generated by SBUtilily uniqueIDForBeacon:.
 *
 *  @return Average of proximity of beaconId.
 */
- (CLProximity)proximityForBeaconId:(NSString *)beaconId;


/**
 *  @return all stored beacon IDs.
 */
- (NSArray *)allBeaconKeys;


/**
 *  Clear all values for all beacon IDs.
 */
- (void)clearCache;


/**
 *  Clear all values for a specific beacon ID.
 */
- (void)clearValuesForBeaconId:(NSString *)beaconId;


@end
